# Generated by Django 4.0 on 2022-01-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='finished_reading',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='started_reading',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
