# Generated by Django 4.0 on 2022-01-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_alter_book_finished_reading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
