# Generated by Django 4.0 on 2022-01-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_book_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
