# Generated by Django 4.0 on 2022-01-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_author_biography_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
